version: "3.7"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    networks:
      - backend
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.1
    networks:
      - backend
    ports:
      - "5601:5601"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.1
    networks:
      - backend
    environment:
      XPACK_MONITORING_ENABLED: "false"
    volumes:
      - ./config/logstash:/usr/share/logstash/pipeline/
      - ./logs:/opt/logs

networks:
  backend:

