---
- name: Create index group template
  uri:
    url: "{{ elastic_host }}/_template/{{ item.key }}"
    method: PUT
    body: "{{ lookup('template', 'create-template.json') }}"
    body_format: json
- name: Check if write alias exists
  uri:
    url: "{{ elastic_host }}/{{ item.key }}-alias"
    method: GET
    status_code: "200, 404"
  register: alias_result
- name: Create write alias
  uri:
    url: "{{ elastic_host }}/%3C{{ item.key }}-%7Bnow%2Fd%7D-000001%3E"
    method: PUT
    body: "{{ lookup('template', 'create-write-alias.json') }}"
    body_format: json
  when: alias_result.status == 404
