---
# tasks file for elastic-ilm
- name: Create lifecycle policies
  uri:
    url: "http://localhost:9200/_ilm/policy/{{ item }}"
    method: PUT
    body: "{{ lookup('template', 'lifecycle-policies/{{ item }}.json.j2') }}"
    body_format: json
  with_items: "{{ lifecycle_polices }}"
- name: "Create index template and write alias"
  include_tasks: create-alias.yml
  with_dict: "{{ template_mappings }}"
