---
# defaults file for elastic-ilm
elastic_host: http://localhost:9200
template_mappings:
  my-index: shortlived-few-docs-rollover
  hello-from-fluent-bit: shortlived-few-docs-rollover
lifecycle_polices:
  - shortlived-few-docs-rollover
